TestModel/urls.py
from django.urls import path

helloworld/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import view,testdb
from django.urls import path,include
#真JB菜 这里需要导模块没注意啊

urlpatterns = [
    url(r'^hello$', view.hello),
    url(r'^landing$',view.landing),
    url(r'^testdb$',testdb.testdb),
    url(r'^admin/',admin.site.urls),
    path('polls/',include('polls.urls')),
    path('knowledge/',include('knowledge.urls')),
]

knowledge/urls.py
from django.urls import path
from .import views
#app name 指明polls的命名空间
app_name = 'knowledge'
urlpatterns = [
	path('knowledge/',views.knowledge,name='knowledge'),
	path('add',views.add,name='add'),
	path('addform/',views.addforms,name='addform'),
	path('contentajax',views.ajaxclick,name='contentajax'),
	path('downfile',views.downloadpycode,name='downfile'),
	#path(r'<int:question_id>/', views.detail, name='detail'),
	#path(r'<int:question_id>/vote/', views.vote, name='vote'),
]

polls/urls.py
from django.urls import path
from .import views
#app name 指明polls的命名空间
app_name = 'polls'
urlpatterns = [
	path('',views.savequestion,name='svaequestion'),
	path('index/',views.index,name='index'),
	path(r'<int:question_id>/', views.detail, name='detail'),
	#path(r'<int:question_id>/vote/', views.vote, name='vote'),
]

TestModel/models.py
from django.db import models

# Create your models here.
class Test(models.Model):
	name = models.CharField(max_length=20)
	def __str__(self):
		return self.name

knowledge/models.py
from django.db import models

# Create your models here.
class Title(models.Model):
	title_text = models.CharField(max_length=50)
	title_date = models.DateTimeField('date published')

class content(models.Model):
	content_title = models.ForeignKey(Title, on_delete=models.CASCADE)
	content_text = models.CharField(max_length=500)
	content_date = models.DateTimeField('date published')
	content_files = models.CharField(max_length=500)

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

knowledge/forms.py
from django import forms

class contentAdd(forms.Form):
	title = forms.CharField(label='标题',max_length=50)
	content = forms.CharField(widget=forms.Textarea(),label='内容',max_length=500)
	codefile = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}),required=False)
	#test = forms.CharField(label='测试',max_length=20)

TestModel/views.py
from django.shortcuts import render
from django.http import Http404
# Create your views here.
from .models import Test

knowledge/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Title
from .models import content
from django.utils import timezone
from django.http import Http404
from .forms import contentAdd
from django.core import files
import datetime
import json
from django.http import FileResponse


# Create your views here.
def knowledge(request):
	title_list = Title.objects.order_by('title_date')
	#print(type(title_list))
	#for t in title_list:
		#print(t.title_date)
	#	t.title_date = t.title_date.strftime('%Y%m%d')
	return render(request,'knowledge/knowledge.html',{'output':title_list})

def ajaxclick(request):
	data = request.POST
	li = data['text'];
	keyid = li.split(',')[1]
	tt = Title.objects.get(id=keyid)
	cc = content.objects.get(content_title=keyid)
	return HttpResponse(json.dumps(cc.content_text+'&'+tt.title_text+'&y'+'&'+cc.content_files),content_type='application/json; charset=utf-8')
	#return render(request,'knowledge/knowledge.html',{'cc':cc)

def add(request):
	return render(request,'knowledge/add.html')

def downloadpycode(request):
	data = request.GET.get("text")
	adir = str(data)
	print(adir)
	file = open(adir,'rb')
	l = data.split("_")
	response =FileResponse(file)
	response['Content-Type']='application/octet-stream'  
	response['Content-Disposition']='attachment;filename='+l[-1]
	return response

def addforms(request):
	if request.method=='POST':
		form = contentAdd(request.POST,request.FILES)
		print(form.errors)
		if form.is_valid():
			#print('into valid')
			datenow = timezone.localtime()
			#print(datenow)
			form_title = form.cleaned_data['title']
			form_content = form.cleaned_data['content']
			sql_title = Title(title_text=form_title,title_date=datenow)
			sql_title.save()
			key = sql_title.title_text+'_'+str(datenow).split(' ')[0]+'_'
			dirs = []
			for i in request.FILES.getlist('codefile'):
				path = 'static/pythoncodeuploadfile/'+key+str(i)
				dirs.append(path)
				handle_uploaded_file(path,i)
			j = "|"
			sql_content = content(content_title=sql_title,content_text=form_content,content_date=datenow,content_files=j.join(dirs))
			sql_content.save()
			
			#if request.FILES['codefile']!='':
			title_list = Title.objects.order_by('title_date')
			return render(request,'knowledge/knowledge.html',{'output':title_list})
		else:
			print('error valid')
	else:
		print('into init')
		form = contentAdd()
	return render(request,'knowledge/add.html',{'form':form})

def handle_uploaded_file(path,i):
	with open(path, 'wb+') as destination:
		for chunk in i.chunks():
			destination.write(chunk)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from django.utils import timezone
from django.http import Http404
# Create your views here.

def savequestion(request):
	q = Question(question_text="What's new?",pub_date=timezone.now())
	q.save()
	return HttpResponse("hello,you're at the polls save question and save 1 question on mysql")

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	output = ','.join([q.question_text for q in latest_question_list])
	return render(request,'polls/index.html',{'output':latest_question_list})

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)

    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question.question_text})

TestModel/templates/detail/index.html
{{ rname }}

knowledge/templates/knowledge/add.html
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>Landing Page | Getting Started with Django</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="alternate icon" type="image/png" href="/static/i/favicon.png">
  <link rel="stylesheet" href="/static/css/amazeui.min.css"/>
  <style>
    .get {
      background: #1E5B94;
      color: #fff;
      text-align: center;
      padding: 100px 0;
    }

    .get-title {
      font-size: 200%;
      border: 2px solid #fff;
      padding: 20px;
      display: inline-block;
    }

    .get-btn {
      background: #fff;
    }

    .detail {
      background: #fff;
    }

    .detail-h2 {
      text-align: center;
      font-size: 150%;
      margin: 40px 0;
    }

    .detail-h3 {
      color: #1f8dd6;
    }

    .detail-p {
      color: #7f8c8d;
    }

    .detail-mb {
      margin-bottom: 30px;
    }

    .hope {
      background: #0bb59b;
      padding: 50px 0;
    }

    .hope-img {
      text-align: center;
    }

    .hope-hr {
      border-color: #149C88;
    }

    .hope-title {
      font-size: 140%;
    }

    .about {
      background: #fff;
      padding: 40px 0;
      color: #7f8c8d;
    }

    .about-color {
      color: #34495e;
    }

    .about-title {
      font-size: 180%;
      padding: 30px 0 50px 0;
      text-align: center;
    }

    .footer p {
      color: #7f8c8d;
      margin: 0;
      padding: 15px 0;
      text-align: center;
      background: #2d3e50;
    }
  </style>
</head>
<body>
<header class="am-topbar am-topbar-fixed-top">
  <div class="am-container">
    <h1 class="am-topbar-brand">
      <a href="#">{{brand}}</a>
    </h1>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-secondary am-show-sm-only"
            data-am-collapse="{target: '#collapse-head'}"><span class="am-sr-only">导航切换</span> <span
        class="am-icon-bars"></span></button>

    <div class="am-collapse am-topbar-collapse" id="collapse-head">
      <ul class="am-nav am-nav-pills am-topbar-nav">
        <li class="am-active"><a href="/landing">首页</a></li>
        <li class="am-dropdown" data-am-dropdown>
          <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
            项目 <span class="am-icon-caret-down"></span>
          </a>
          <ul class="am-dropdown-content">
       <!--     <li class="am-dropdown-header">标题</li>   -->
            <li><a href="/hello">1. Python3</a></li>
            <li><a href="/polls/index">2. Django2</a></li>
          </ul>
        </li>
        <li><a href="#">更多</a></li>
      </ul>

      <div class="am-topbar-right">
        <button class="am-btn am-btn-secondary am-topbar-btn am-btn-sm"><span class="am-icon-pencil"></span> 注册</button>
      </div>

      <div class="am-topbar-right">
        <button class="am-btn am-btn-primary am-topbar-btn am-btn-sm"><span class="am-icon-user"></span> 登录</button>
      </div>
    </div>
  </div>
</header>

<div class="about">
  <div class="am-g am-container">
    <div class="am-u-lg-12">

          <form class="am-form" action="/knowledge/addform/" method="POST"  enctype="multipart/form-data" >
          <!--  <label for="title" class="about-color">标题</label>
            <input id="title" type="text" value="{{current_title}}">
            <br/>
            <label for="content" class="about-color">内容</label>
            <textarea id="content" style="height:240px" value="{{current_content}}"></textarea>
          -->
            {% csrf_token %}
            {{ form }}
            <br/>
            <button type="submit" class="am-btn am-btn-primary am-btn-sm"><i class="am-icon-button"></i> 提 交</button>
          </form>
          <hr class="am-article-divider am-show-sm-only">
    </div>
  </div>
</div>

<footer class="footer">
  <p>© 2018 <i class="am-icon-github am-icon-sm "></i> <a href="https://github.com/hy0510hy/learndjango" target="_blank">GitHub Page.</a> Code in this repository. </p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/static/js/jquery.min.js"></script>
<!--<![endif]-->
<script src="/static/js/amazeui.min.js"></script>
</body>
</html>

knowledge/templates/knowledge/knowledge.html
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>Landing Page | Getting Started with Django</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="alternate icon" type="image/png" href="/static/i/favicon.png">
  <link rel="stylesheet" href="/static/css/amazeui.min.css"/>
  <style>
    .get {
      background: #1E5B94;
      color: #fff;
      text-align: center;
      padding: 100px 0;
    }

    .get-title {
      font-size: 200%;
      border: 2px solid #fff;
      padding: 20px;
      display: inline-block;
    }

    .get-btn {
      background: #fff;
    }

    .detail {
      background: #fff;
    }

    .detail-h2 {
      text-align: center;
      font-size: 150%;
      margin: 40px 0;
    }

    .detail-h3 {
      color: #1f8dd6;
    }

    .detail-p {
      color: #7f8c8d;
    }

    .detail-mb {
      margin-bottom: 30px;
    }

    .hope {
      background: #0bb59b;
      padding: 50px 0;
    }

    .hope-img {
      text-align: center;
    }

    .hope-hr {
      border-color: #149C88;
    }

    .hope-title {
      font-size: 140%;
    }

    .about {
      background: #fff;
      padding: 40px 0;
      color: #7f8c8d;
    }

    .about-color {
      color: #34495e;
    }

    .about-title {
      font-size: 180%;
      padding: 30px 0 50px 0;
      text-align: center;
    }

    .footer p {
      color: #7f8c8d;
      margin: 0;
      padding: 15px 0;
      text-align: center;
      background: #2d3e50;
    }
  </style>
</head>
<body>
<header class="am-topbar am-topbar-fixed-top">
  <div class="am-container">
    <h1 class="am-topbar-brand">
      <a href="#">{{brand}}</a>
    </h1>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-secondary am-show-sm-only"
            data-am-collapse="{target: '#collapse-head'}"><span class="am-sr-only">导航切换</span> <span
        class="am-icon-bars"></span></button>

    <div class="am-collapse am-topbar-collapse" id="collapse-head">
      <ul class="am-nav am-nav-pills am-topbar-nav">
        <li class="am-active"><a href="/landing">首页</a></li>
        <li class="am-dropdown" data-am-dropdown>
          <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
            项目 <span class="am-icon-caret-down"></span>
          </a>
          <ul class="am-dropdown-content">
       <!--     <li class="am-dropdown-header">标题</li>   -->
            <li><a href="/hello">1. Python3</a></li>
            <li><a href="/polls/index">2. Django2</a></li>
          </ul>
        </li>
        <li><a href="#">更多</a></li>
      </ul>

      <div class="am-topbar-right">
        <button class="am-btn am-btn-secondary am-topbar-btn am-btn-sm"><span class="am-icon-pencil"></span> 注册</button>
      </div>

      <div class="am-topbar-right">
        <button class="am-btn am-btn-primary am-topbar-btn am-btn-sm"><span class="am-icon-user"></span> 登录</button>
      </div>
    </div>
  </div>
</header>

<div class="about">
  <div class="am-g am-container">
    <div class="am-u-lg-8">
      <label for="name" class="about-color">搜索</label>
      <input id="search" type="text">
      <button type="submit" class="am-btn am-btn-primary am-btn-sm"><i class="am-icon-check"></i>搜 索</button>
    </div>
    <div class="am-u-lg-4">
      <button type="submit" onclick="location.href='/knowledge/addform/'" class="am-btn am-btn-primary am-btn-sm"><i class="am-icon-add"></i>新 增</button>
    </div>
  </div>
    <div class="am-g">
      <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
      <div class="am-u-lg-4 am-u-md-4 am-u-sm-4">

          <label for="name" class="about-color">标题</label>
          {% if output %}
            <ul>
            {% for title in output %}
              <li><a href="javacript:void(0)" title="{{title.title_date}}" onclick='Ajaxclick("{{title.title_text}},{{title.id}}")' >{{ title.title_text }}</a></li>
            {% endfor %}
            </ul>
          {% else %}
            <p>No content are available.</p>
          {% endif %}

        <hr class="am-article-divider am-show-sm-only">
      </div>

      <div  class="am-u-lg-8 am-u-md-8 am-u-sm-8">
        <p id="la"></p>
        <p id='p' ></p>
        <p id='h' hidden="True" >11</p>
        <pre id='c' >
          这是主页哦，坚持PYTHON基础语法的学习。并且把每天学到的知识提交到本页。
          学习使我快乐。<img src='/static/images/study1.jpg' ></img><img src='/static/images/study2.jpg' ></img>
          学习使我快乐。<img src='/static/images/study3.jpg' ></img><img src='/static/images/study4.jpg' ></img>
          学习使我快乐。<img src='/static/images/study5.jpg' ></img>

        </pre>
      </div>
    </div>
  </div>


<footer class="footer">
  <p>© 2018 <i class="am-icon-github am-icon-sm "></i> <a href="https://github.com/hy0510hy/learndjango" target="_blank">GitHub Page.</a> Code in this repository. </p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/static/js/jquery.min.js"></script>
<!--<![endif]-->
<script src="/static/js/amazeui.min.js"></script>
<script type="text/javascript">

  function addA(dir){
    var l = dir.split("_");
    var wl = '<a href="/knowledge/downfile?text='+dir+'"'+' rel="external nofollow" >'+l[l.length-1]+'</a>&nbsp; &nbsp; &nbsp; ';
    return wl;
  }

  $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
  function Ajaxclick(text,keyid){
    $.ajax({
      url:"/knowledge/contentajax",
      type:'POST',
      tradition:true,
      data:{'text':text,'keyid':keyid},
      success: function(arg){
        d = arg.split('&');
        $("#c").html(d[0]);
        $("#p").html(d[1]);
        if(d[2]=="y"){
          $("#d").show();
        }else{
          $("#d").hide();
        }
        $("#la").empty();
        var l = d[3].split("|");
        for(var i=0;i<l.length;i++){
          $("#la").append(addA(l[i]));
        }
      }
    });
  }
</script>

<script type="text/javascript">

  $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
  function Ajaxdownfile(){
    title = $("#h").html();
    $.ajax({
      url:"/knowledge/downfile",
      type:'POST',
      tradition:true,
      data:{'text':title},
      success: function(arg){
        alert(arg);
      }
    });
  }
</script>
</body>
</html>

polls/templates/polls/detail.html
{{ question }}

polls/templates/polls/index.html
{% if output %}
    <ul>
    {% for question in output %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/hello.html
<h1>{{hello}}</h1>
<ul>
{% for li in listnum reversed %}
	<li>{{li}}</li>
{% endfor %}
</ul>
<ul>
{% for li in cut %}
	<li>{{li}}</li>
{% endfor %}
</ul>

templates/landing.html
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>Landing Page | Getting Started with Django</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="alternate icon" type="image/png" href="/static/i/favicon.png">
  <link rel="stylesheet" href="/static/css/amazeui.min.css"/>
  <style>
    .get {
      background: #1E5B94;
      color: #fff;
      text-align: center;
      padding: 100px 0;
    }

    .get-title {
      font-size: 200%;
      border: 2px solid #fff;
      padding: 20px;
      display: inline-block;
    }

    .get-btn {
      background: #fff;
    }

    .detail {
      background: #fff;
    }

    .detail-h2 {
      text-align: center;
      font-size: 150%;
      margin: 40px 0;
    }

    .detail-h3 {
      color: #1f8dd6;
    }

    .detail-p {
      color: #7f8c8d;
    }

    .detail-mb {
      margin-bottom: 30px;
    }

    .hope {
      background: #0bb59b;
      padding: 50px 0;
    }

    .hope-img {
      text-align: center;
    }

    .hope-hr {
      border-color: #149C88;
    }

    .hope-title {
      font-size: 140%;
    }

    .about {
      background: #fff;
      padding: 40px 0;
      color: #7f8c8d;
    }

    .about-color {
      color: #34495e;
    }

    .about-title {
      font-size: 180%;
      padding: 30px 0 50px 0;
      text-align: center;
    }

    .footer p {
      color: #7f8c8d;
      margin: 0;
      padding: 15px 0;
      text-align: center;
      background: #2d3e50;
    }
  </style>
</head>
<body>
<header class="am-topbar am-topbar-fixed-top">
  <div class="am-container">
    <h1 class="am-topbar-brand">
      <a href="#">{{brand}}</a>
    </h1>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-secondary am-show-sm-only"
            data-am-collapse="{target: '#collapse-head'}"><span class="am-sr-only">导航切换</span> <span
        class="am-icon-bars"></span></button>

    <div class="am-collapse am-topbar-collapse" id="collapse-head">
      <ul class="am-nav am-nav-pills am-topbar-nav">
        <li class="am-active"><a href="./landing">首页</a></li>
        <li class="am-dropdown" data-am-dropdown>
          <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
            项目 <span class="am-icon-caret-down"></span>
          </a>
          <ul class="am-dropdown-content">
       <!--     <li class="am-dropdown-header">标题</li>   -->
            <li><a href="./hello">1. Python3</a></li>
            <li><a href="./polls/index">2. Django2</a></li>
          </ul>
        </li>
        <li><a href="#">更多</a></li>
      </ul>

      <div class="am-topbar-right">
        <button class="am-btn am-btn-secondary am-topbar-btn am-btn-sm"><span class="am-icon-pencil"></span> 注册</button>
      </div>

      <div class="am-topbar-right">
        <button class="am-btn am-btn-primary am-topbar-btn am-btn-sm"><span class="am-icon-user"></span> 登录</button>
      </div>
    </div>
  </div>
</header>

<div class="get">
  <div class="am-g">
    <div class="am-u-lg-12">
      <h1 class="get-title">开始PYTHON的学习之旅</h1>

      <p>
        每天都在进步中。。。
      </p>

      <p>
        <a href="./knowledge/knowledge" class="am-btn am-btn-sm get-btn">获取新技能√get</a>
      </p>
    </div>
  </div>
</div>

<div class="detail">
  <div class="am-g am-container">
    <div class="am-u-lg-12">
      <h2 class="detail-h2">从基础开始 、认真学习，以此网站的形式去实现!</h2>

      <div class="am-g">
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">

          <h3 class="detail-h3">
            <i class="am-icon-mobile am-icon-sm"></i>
            为移动而生
          </h3>

          <p class="detail-p">
            Amaze UI 采用业内先进的 mobile first 理念，从小屏逐步扩展到大屏，最终实现所有屏幕适配，适应移动互联潮流。
          </p>
        </div>
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">
          <h3 class="detail-h3">
            <i class="am-icon-cogs am-icon-sm"></i>
            组件丰富，模块化
          </h3>

          <p class="detail-p">
            Amaze UI 含近 20 个 CSS 组件、10 个 JS 组件，更有 17 款包含近 60 个主题的 Widgets，可快速构建界面出色、体验优秀的跨屏页面，大幅度提升你的开发效率。
          </p>
        </div>
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">
          <h3 class="detail-h3">
            <i class="am-icon-check-square-o am-icon-sm"></i>
            本地化支持
          </h3>

          <p class="detail-p">
            相比国外的前端框架，Amaze UI 专注解决中文排版优化问题，根据操作系统调整字体，实现最佳中文排版效果；针对国内主流浏览器及 App 内置浏览器提供更好的兼容性支持，为你节省大量兼容性调试时间。
          </p>
        </div>
        <div class="am-u-lg-3 am-u-md-6 am-u-sm-12 detail-mb">
          <h3 class="detail-h3">
            <i class="am-icon-send-o am-icon-sm"></i>
            轻量级，高性能
          </h3>

          <p class="detail-p">
            Amaze UI 非常注重性能，基于轻量的 Zepto.js 开发，并使用 CSS3 来做动画交互，平滑、高效，更适合移动设备，让你的 Web 应用可以高速载入。
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="hope">
  <div class="am-g am-container">
    <div class="am-u-lg-4 am-u-md-6 am-u-sm-12 hope-img">
      <img src="/static/img/landing.png" alt="" data-am-scrollspy="{animation:'slide-left', repeat: false}">
      <hr class="am-article-divider am-show-sm-only hope-hr">
    </div>
    <div class="am-u-lg-8 am-u-md-6 am-u-sm-12">
      <h2 class="hope-title">同我们一起打造你的前端框架</h2>

      <p>
        在知识爆炸的年代，我们不愿成为知识的过客，拥抱开源文化，发挥社区的力量，参与到Amaze Ui开源项目能获得自我提升。
      </p>
    </div>
  </div>
</div>

<div class="about">
  <div class="am-g am-container">
    <div class="am-u-lg-12">
      <h2 class="about-title about-color">Amaze UI 崇尚开放、自由，非常欢迎大家的参与</h2>

      <div class="am-g">
        <div class="am-u-lg-6 am-u-md-4 am-u-sm-12">
          <form class="am-form">
            <label for="name" class="about-color">你的姓名</label>
            <input id="name" type="text">
            <br/>
            <label for="email" class="about-color">你的邮箱</label>
            <input id="email" type="email">
            <br/>
            <label for="message" class="about-color">你的留言</label>
            <textarea id="message"></textarea>
            <br/>
            <button type="submit" class="am-btn am-btn-primary am-btn-sm"><i class="am-icon-check"></i> 提 交</button>
          </form>
          <hr class="am-article-divider am-show-sm-only">
        </div>

        <div class="am-u-lg-6 am-u-md-8 am-u-sm-12">
          <h4 class="about-color">关于我们</h4>

          <p>AllMobilize Inc (美通云动科技有限公司)
            由前微软美国总部IE浏览器核心研发团队成员及移动互联网行业专家在美国西雅图创立，旨在解决网页在不同移动设备屏幕上的适配问题。基于国际专利技术并结合最前沿的HTML5技术，云适配解决方案可以帮助企业快速将桌面版网站适配到各种移动设备终端的屏幕上，不仅显著地提高了企业网站的用户体验以及销售转化率，而且大幅度地节省了企业开发和维护移动网站的费用。</p>
          <h4 class="about-color">团队介绍</h4>

          <p>AllMobilize Inc 获得了微软创投孵化器的支持，其领先科技已得到全球多家企业及机构的认可与信赖，客户包括全球500强企业、美国政府、国内政府机关、国内外上市公司、以及互联网标准化组织W3C。</p>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="footer">
  <p>© 2018 <i class="am-icon-github am-icon-sm "></i> <a href="https://github.com/hy0510hy/learndjango" target="_blank">GitHub Page.</a> Code in this repository. </p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/static/js/jquery.min.js"></script>
<!--<![endif]-->
<script src="/static/js/amazeui.min.js"></script>
</body>
</html>